[package]
name = "rsgss-binding-magnus"
version = "0.1.0"
edition = "2021"

[dependencies]
magnus = "0.6.2"

librgss = { version = "0.1.0", path = "../librgss/" }

[features]
embed = ["magnus/embed"]
static = ["magnus/ruby-static"]
